<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fgd</string>
		<string>qc</string>
		<string>vdf</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		 /\*\*(?!\*)
		|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
	</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Valve Data File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.fgd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.fgd</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fgd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fgd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.fgd</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fgd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fgd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.fgd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.fgd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(integer|choices|string|flags|target_destination|target_source|color255|studio|sprite|sound|size)\b</string>
			<key>name</key>
			<string>storage.type.fgd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$(alwayscollapse|animation|animblocksize|append|attachment|autocenter|bbox|body|bodygroup|bonemerge|calctransitions|cbox|cd|cdmaterials|cliptotextures|cmdlist|collapsebones|collisionjoints|collisionmodel|collisiontext|contents|continue|controller|declareanimation|declaresequence|definebone|definemacro|externaltextures|eyeposition|forcephonemecrossfade|forcereal|gamma|hbox|hboxset|hgroup|hierarchy|ikautoplaylock|ikchain|illumposition|include|includemodel|insertbone|jigglebone|jointcontents|jointsurfaceprop|keyvalues|limitrotation|lockbonelengths|lockdefinebones|lod|model|modelname|mostlyopaque|noforcedfade|obsolete|opaque|origin|popd|poseparameter|prepend|proceduralbones|pushd|realignbones|renamebone|renamematerial|root|scale|screenalign|sequence|skipboneinbbox|staticprop|surfaceprop|texturegroup|upaxis|weightlist|zbrush)\b</string>
			<key>name</key>
			<string>variable.language.fgd</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fgd</string>
	<key>uuid</key>
	<string>8358ee91-9694-439a-8616-b2ea7642f5b8</string>
</dict>
</plist>
